from fastapi import FastAPI, UploadFile, File, Form, HTTPException, BackgroundTasks, Request
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional, Dict
import shutil
import os
import tempfile
import random
import uuid
import time
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from pypdf import PdfReader

from backend.core.llm import get_llm_client
from backend.core.generator import FlashcardGenerator
from backend.core.schemas import DeckConfig
from backend.core.anki import AnkiDeckBuilder
from backend.core.images import get_image_generator
from backend.core.config import settings
from backend.core.logging import logger
from backend.core.auth import get_current_user, check_quota, increment_quota

# Setup Rate Limiting
limiter = Limiter(key_func=get_remote_address)
app = FastAPI(title=settings.APP_NAME, version="1.0.0")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Setup CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-Memory Job Store (Note: Doesn't persist across restarts or serverless instances)
jobs: Dict[str, dict] = {}

def cleanup_file(path: str):
    try:
        if os.path.exists(path):
            os.remove(path)
            logger.info(f"Cleaned up {path}")
    except Exception as e:
        logger.error(f"Cleaning up {path} failed: {e}")

def get_real_api_key(provider: str, user_key: Optional[str] = None) -> str:
    # 1. User provided key (BYOK)
    if user_key and user_key.strip():
        return user_key
    
    # 2. System ENV key
    env_key = getattr(settings, f"{provider.upper()}_API_KEY", None)
    if env_key:
        return env_key
        
    raise ValueError(f"No API Key found for {provider}. Please provide one.")

def generate_deck_task(job_id: str, text: str, config_data: dict, provider: str, user_key: str, images_enabled: bool):
    try:
        jobs[job_id]["status"] = "processing"
        
        # 1. Initialize LLM
        api_key = get_real_api_key(provider, user_key)
        llm_client = get_llm_client(provider, api_key, config_data.get('model_name'))
        generator = FlashcardGenerator(llm_client)

        # 2. Generate Cards
        logger.info(f"Job {job_id}: Generating cards with {provider}...")
        config = DeckConfig(**config_data)
        cards = generator.generate_flashcards(text, config)
        
        if not cards:
            raise ValueError("No cards generated by AI.")

        # 3. Generate Images (if enabled)
        image_map = {}
        if images_enabled and settings.ENABLE_IMAGE_GEN:
            logger.info(f"Job {job_id}: Generating images...")
            img_key = api_key if provider == "gemini" else os.getenv("GEMINI_API_KEY") 
            if img_key:
                img_gen = get_image_generator("gemini", img_key)
                if img_gen:
                    temp_dir = tempfile.mkdtemp()
                    for i, card in enumerate(cards):
                        if card.image_prompt:
                            img_filename = f"card_{i}_{random.randint(1000,9999)}.png"
                            img_path = os.path.join(temp_dir, img_filename)
                            # Simulating basic concurrency here would be better, but sequential for safety
                            if img_gen.generate_image(card.image_prompt, img_path):
                                image_map[i] = img_path

        # 4. Create .apkg
        builder = AnkiDeckBuilder()
        output_filename = f"{config.name.replace(' ', '_')}.apkg"
        output_path = os.path.join(tempfile.gettempdir(), f"{job_id}_{output_filename}")
        
        if image_map:
            builder.create_apkg_with_images(cards, config.name, output_path, image_map)
        else:
            builder.create_apkg(cards, config.name, output_path)
            
        jobs[job_id]["status"] = "completed"
        jobs[job_id]["file_path"] = output_path
        jobs[job_id]["filename"] = output_filename
        logger.info(f"Job {job_id}: Completed successfully. File at {output_path}")
        
    except Exception as e:
        logger.error(f"Job {job_id} Failed: {e}")
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = str(e)


@app.get("/api/config")
def get_config():
    """Returns public configuration for the frontend."""
    return {
        "enable_ollama": settings.ENABLE_OLLAMA,
        "enable_images": settings.ENABLE_IMAGE_GEN,
        "env": settings.ENV,
        # Frontend needs Supabase Config for Auth
        "supabase_url": os.getenv("SUPABASE_URL"),
        "supabase_anon_key": os.getenv("SUPABASE_KEY") # Assuming the user provided key is usable by frontend
    }

@app.post("/generate")
@limiter.limit(settings.RATE_LIMIT_FREE)
async def submit_job(
    request: Request,
    background_tasks: BackgroundTasks,
    file: Optional[UploadFile] = File(None),
    text: Optional[str] = Form(None),
    provider: str = Form("gemini"),
    model: Optional[str] = Form(None),
    api_key: Optional[str] = Form(None),
    deck_name: str = Form("MeshCards Deck"),
    difficulty: str = Form("Intermediate"),
    style: str = Form("Mixed"),
    max_cards: int = Form(20),
    images: bool = Form(False),
    custom_instructions: Optional[str] = Form(None),
    authorization: Optional[str] = Header(None)
):
    # 1. Auth & Quota Check
    try:
        user = await get_current_user(authorization)
        if user:
            check_quota(user.id)
            increment_quota(user.id)
        else:
            raise HTTPException(status_code=401, detail="Please Sign In to generate flashcards.")
    except Exception as e:
        logger.error(f"Auth error: {e}")
        # If running locally without supabase keys, user might get stuck.
        # But per requirements we enforce 3 decks.
        raise e

    if not file and not text:
        raise HTTPException(status_code=400, detail="Either file or text must be provided")

    # Read Input
    input_text = ""
    try:
        if text:
            input_text = text
        elif file:
            suffix = os.path.splitext(file.filename)[1]
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
                shutil.copyfileobj(file.file, tmp_file)
                tmp_path = tmp_file.name
            
            if suffix.lower() == ".pdf":
                 reader = PdfReader(tmp_path)
                 for page in reader.pages:
                     extract = page.extract_text()
                     if extract:
                        input_text += extract + "\n"
            else:
                with open(tmp_path, "r", encoding="utf-8") as f:
                    input_text = f.read()
            
            cleanup_file(tmp_path)
    except Exception as e:
        logger.error(f"Input reading failed: {e}")
        raise HTTPException(status_code=400, detail=f"Failed to read input: {str(e)}")

    if not input_text.strip():
        raise HTTPException(status_code=400, detail="Input text is empty (or PDF was scanned image)")
    
    # Create Job
    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        "status": "pending",
        "created_at": time.time()
    }
    
    config_data = {
        "name": deck_name,
        "difficulty": difficulty,
        "style": style,
        "max_cards": max_cards,
        "model_name": model,
        "custom_instructions": custom_instructions
    }
    
    logger.info(f"Job {job_id}: Accepted. Provider={provider}")
    
    # Start Task
    background_tasks.add_task(
        generate_deck_task, 
        job_id, 
        input_text, 
        config_data, 
        provider, 
        api_key, 
        images
    )
    
    return {"job_id": job_id, "status": "pending"}

@app.get("/status/{job_id}")
def get_status(job_id: str):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    return {
        "job_id": job_id,
        "status": job["status"],
        "error": job.get("error")
    }

@app.get("/download/{job_id}")
def download_deck(job_id: str, background_tasks: BackgroundTasks):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    if job["status"] != "completed":
        raise HTTPException(status_code=400, detail="Job not completed")
    
    file_path = job["file_path"]
    filename = job["filename"]
    
    # Schedule cleanup after response
    background_tasks.add_task(cleanup_file, file_path)
    
    # Also clean up job from memory to prevent leak
    if job_id in jobs:
        del jobs[job_id]
    
    logger.info(f"Serving download for Job {job_id}")
    return FileResponse(
        file_path, 
        media_type="application/octet-stream", 
        filename=filename
    )

# Mount static files - MUST BE LAST
cwd = os.getcwd()
frontend_dist = os.path.join(cwd, "frontend", "dist")
frontend_legacy = os.path.join(cwd, "frontend_legacy")

logger.info(f"CWD: {cwd}")
if os.path.exists(frontend_dist):
    logger.info(f"Mounting React Frontend from {frontend_dist}")
    app.mount("/", StaticFiles(directory=frontend_dist, html=True), name="static")
elif os.path.exists(frontend_legacy): 
    logger.info(f"Mounting Legacy Frontend from {frontend_legacy}")
    app.mount("/", StaticFiles(directory=frontend_legacy, html=True), name="static")
else:
    logger.warning("No frontend found!")
