from fastapi import FastAPI, UploadFile, File, Form, HTTPException, BackgroundTasks, Request, Header
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional, Dict
import shutil
import os
import tempfile
import random
import uuid
import time
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
import urllib.request
import json
import traceback
from pypdf import PdfReader

from backend.core.llm import get_llm_client
from backend.core.generator import FlashcardGenerator
from backend.core.schemas import DeckConfig, FeedbackRequest


from backend.core.anki import AnkiDeckBuilder
from backend.core.images import get_image_generator
from backend.core.config import settings
from backend.core.logging import logger
from backend.core.auth import get_current_user, check_quota, increment_quota

# Setup Rate Limiting
limiter = Limiter(key_func=get_remote_address)
app = FastAPI(title=settings.APP_NAME, version="1.0.0")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Setup CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-Memory Job Store (Note: Doesn't persist across restarts or serverless instances)
jobs: Dict[str, dict] = {}

def cleanup_file(path: str):
    try:
        if os.path.exists(path):
            os.remove(path)
            logger.info(f"Cleaned up {path}")
    except Exception as e:
        logger.error(f"Cleaning up {path} failed: {e}")

def get_real_api_key(provider: str, user_key: Optional[str] = None) -> str:
    # 1. User provided key (BYOK)
    if user_key and user_key.strip():
        return user_key
    
    # 2. System ENV key
    env_key = getattr(settings, f"{provider.upper()}_API_KEY", None)
    if env_key:
        return env_key
        
    raise ValueError(f"No API Key found for {provider}. Please provide one.")

def log_error_to_github(e: Exception, context: str = ""):
    """Logs full error details to a GitHub Issue and returns a simplified message."""
    # 1. Capture Full Traceback and Environment
    tb_str = traceback.format_exc()
    error_type = type(e).__name__
    error_msg = str(e)
    
    full_log = f"""**Error:** {error_type}: {error_msg}
**Context:** {context}
**Environment:** {settings.ENV}
**Timestamp:** {time.ctime()}

**Traceback:**
```python
{tb_str}
```
"""
    # 2. Log locally/console
    logger.error(f"FATAL ERROR ({context}): {error_msg}\n{tb_str}")
    
    # 3. Create GitHub Issue
    if settings.GITHUB_TOKEN and settings.GITHUB_REPO:
        try:
            url = f"https://api.github.com/repos/{settings.GITHUB_REPO}/issues"
            data = {
                "title": f"Error Log: {error_type} in {context}",
                "body": full_log,
                "labels": ["error-log", "auto-generated"]
            }
            req = urllib.request.Request(
                url, 
                data=json.dumps(data).encode("utf-8"), 
                headers={
                    "Authorization": f"token {settings.GITHUB_TOKEN}",
                    "Accept": "application/vnd.github.v3+json",
                    "User-Agent": settings.APP_NAME
                }
            )
            with urllib.request.urlopen(req) as res:
                if res.status == 201:
                    logger.info("Error log posted to GitHub Issues")
        except Exception as gh_e:
            logger.error(f"Failed to log error to GitHub: {gh_e}")

    # 4. Return simplified info for frontend
    return f"Error Code: {error_type} | Title: {context} Failed"

def generate_deck_task(job_id: str, text: str, config_data: dict, provider: str, user_key: str, images_enabled: bool):
    try:
        jobs[job_id]["status"] = "processing"
        
        # 1. Initialize LLM
        api_key = get_real_api_key(provider, user_key)
        llm_client = get_llm_client(provider, api_key, config_data.get('model_name'))
        generator = FlashcardGenerator(llm_client)

        # 2. Generate Cards
        logger.info(f"Job {job_id}: Generating cards with {provider}...")
        config = DeckConfig(**config_data)
        cards = generator.generate_flashcards(text, config)
        
        if not cards:
            raise ValueError("No cards generated by AI.")

        # 3. Generate Images (if enabled)
        image_map = {}
        if images_enabled and settings.ENABLE_IMAGE_GEN:
            logger.info(f"Job {job_id}: Generating images...")
            img_key = api_key if provider == "gemini" else os.getenv("GEMINI_API_KEY") 
            if img_key:
                img_gen = get_image_generator("gemini", img_key)
                if img_gen:
                    temp_dir = tempfile.mkdtemp()
                    for i, card in enumerate(cards):
                        if card.image_prompt:
                            img_filename = f"card_{i}_{random.randint(1000,9999)}.png"
                            img_path = os.path.join(temp_dir, img_filename)
                            # Simulating basic concurrency here would be better, but sequential for safety
                            if img_gen.generate_image(card.image_prompt, img_path):
                                image_map[i] = img_path

        # 4. Create .apkg
        builder = AnkiDeckBuilder()
        output_filename = f"{config.name.replace(' ', '_')}.apkg"
        output_path = os.path.join(tempfile.gettempdir(), f"{job_id}_{output_filename}")
        
        if image_map:
            builder.create_apkg_with_images(cards, config.name, output_path, image_map)
        else:
            builder.create_apkg(cards, config.name, output_path)
            
        jobs[job_id]["status"] = "completed"
        jobs[job_id]["file_path"] = output_path
        jobs[job_id]["filename"] = output_filename
        logger.info(f"Job {job_id}: Completed successfully. File at {output_path}")
        
    except Exception as e:
        # Log full error to GitHub and get simplified message
        simple_error = log_error_to_github(e, context=f"Job {job_id}")
        
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = simple_error


@app.post("/api/feedback")
async def submit_feedback(feedback: FeedbackRequest):
    # 1. Log to console (Basis)
    log_msg = f"FEEDBACK [{feedback.type}]: {feedback.message} ({feedback.rating}/5) - {feedback.email}"
    logger.info(log_msg)
    
    # 2. Local Log (Dev)
    if settings.ENV != "production":
        try:
            with open("feedback.log", "a") as f:
                f.write(f"[{time.ctime()}] {log_msg}\n")
        except: pass
        
    # 3. GitHub Issue Integration
    if settings.GITHUB_TOKEN and settings.GITHUB_REPO:
        try:
            url = f"https://api.github.com/repos/{settings.GITHUB_REPO}/issues"
            data = {
                "title": f"User Feedback: {feedback.type.title()}",
                "body": f"**Rating:** {feedback.rating}/5\n**Email:** {feedback.email}\n**Type:** {feedback.type}\n\n**Message:**\n{feedback.message}",
                "labels": ["feedback", "user-submitted"]
            }
            req = urllib.request.Request(
                url, 
                data=json.dumps(data).encode("utf-8"), 
                headers={
                    "Authorization": f"token {settings.GITHUB_TOKEN}",
                    "Accept": "application/vnd.github.v3+json",
                    "User-Agent": settings.APP_NAME
                }
            )
            with urllib.request.urlopen(req) as res:
                if res.status == 201:
                    logger.info("Feedback posted to GitHub Issues")
        except Exception as e:
            logger.error(f"Failed to post feedback to GitHub: {e}")

    return {"status": "received", "message": "Feedback submitted."}

@app.get("/api/config")
def get_config():
    """Returns public configuration for the frontend."""
    return {
        "enable_ollama": settings.ENABLE_OLLAMA,
        "enable_images": settings.ENABLE_IMAGE_GEN,
        "env": settings.ENV,
        # Frontend needs Supabase Config for Auth
        "supabase_url": settings.SUPABASE_URL,
        "supabase_anon_key": settings.SUPABASE_KEY
    }

@app.post("/generate")
@limiter.limit(settings.RATE_LIMIT_FREE)
async def submit_job(
    request: Request,
    background_tasks: BackgroundTasks,
    file: Optional[UploadFile] = File(None),
    text: Optional[str] = Form(None),
    provider: str = Form("gemini"),
    model: Optional[str] = Form(None),
    api_key: Optional[str] = Form(None),
    deck_name: str = Form("MeshCards Deck"),
    difficulty: str = Form("Intermediate"),
    style: str = Form("Mixed"),
    max_cards: int = Form(20),
    images: bool = Form(False),
    custom_instructions: Optional[str] = Form(None),
    authorization: Optional[str] = Header(None)
):
    # 1. Auth & Quota Check
    try:
        user = await get_current_user(authorization)
        if user:
            check_quota(user.id)
            increment_quota(user.id)
        else:
            raise HTTPException(status_code=401, detail="Please Sign In to generate flashcards.")
    except Exception as e:
        logger.error(f"Auth error: {e}")
        # If running locally without supabase keys, user might get stuck.
        # But per requirements we enforce 3 decks.
        raise e

    if not file and not text:
        raise HTTPException(status_code=400, detail="Either file or text must be provided")

    # Read Input
    input_text = ""
    try:
        if text:
            input_text = text
        elif file:
            suffix = os.path.splitext(file.filename)[1]
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
                shutil.copyfileobj(file.file, tmp_file)
                tmp_path = tmp_file.name
            
            if suffix.lower() == ".pdf":
                 reader = PdfReader(tmp_path)
                 for page in reader.pages:
                     extract = page.extract_text()
                     if extract:
                        input_text += extract + "\n"
            else:
                with open(tmp_path, "r", encoding="utf-8") as f:
                    input_text = f.read()
            
            cleanup_file(tmp_path)
    except Exception as e:
        logger.error(f"Input reading failed: {e}")
        raise HTTPException(status_code=400, detail=f"Failed to read input: {str(e)}")

    if not input_text.strip():
        raise HTTPException(status_code=400, detail="Input text is empty (or PDF was scanned image)")
    
    # Create Job
    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        "status": "pending",
        "created_at": time.time()
    }
    
    config_data = {
        "name": deck_name,
        "difficulty": difficulty,
        "style": style,
        "max_cards": max_cards,
        "model_name": model,
        "custom_instructions": custom_instructions
    }
    
    logger.info(f"Job {job_id}: Accepted. Provider={provider}")
    
    # Start Task
    background_tasks.add_task(
        generate_deck_task, 
        job_id, 
        input_text, 
        config_data, 
        provider, 
        api_key, 
        images
    )
    
    return {"job_id": job_id, "status": "pending"}

@app.get("/status/{job_id}")
def get_status(job_id: str):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    return {
        "job_id": job_id,
        "status": job["status"],
        "error": job.get("error")
    }

@app.get("/download/{job_id}")
def download_deck(job_id: str, background_tasks: BackgroundTasks):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    if job["status"] != "completed":
        raise HTTPException(status_code=400, detail="Job not completed")
    
    file_path = job["file_path"]
    filename = job["filename"]
    
    # Schedule cleanup after response
    background_tasks.add_task(cleanup_file, file_path)
    
    # Also clean up job from memory to prevent leak
    if job_id in jobs:
        del jobs[job_id]
    
    logger.info(f"Serving download for Job {job_id}")
    return FileResponse(
        file_path, 
        media_type="application/octet-stream", 
        filename=filename
    )

# Mount static files - MUST BE LAST
# Mount static files - MUST BE LAST
cwd = os.getcwd()
frontend_dist = os.path.join(cwd, "frontend", "dist")

if os.path.exists(frontend_dist):
    logger.info(f"Mounting React Frontend from {frontend_dist}")
    
    # 1. Mount assets explicitly so they are served correctly
    app.mount("/assets", StaticFiles(directory=os.path.join(frontend_dist, "assets")), name="assets")

    # Explicit favicon route to prevent 404/fallback issues
    @app.get("/favicon.ico", include_in_schema=False)
    async def favicon():
        return FileResponse(
            os.path.join(frontend_dist, "favicon.ico"), 
            headers={"Cache-Control": "no-cache, no-store, must-revalidate"}
        )

    # 2. Catch-all route for SPA (Single Page Application)
    # This serves existing files (favicon.ico, robots.txt) or falls back to index.html
    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        potential_path = os.path.join(frontend_dist, full_path)
        if os.path.exists(potential_path) and os.path.isfile(potential_path):
            return FileResponse(potential_path)
        
        # Disable caching for index.html so updates are seen immediately
        return FileResponse(
            os.path.join(frontend_dist, "index.html"), 
            headers={"Cache-Control": "no-cache, no-store, must-revalidate"}
        )

else:
    logger.warning("No frontend found! Run 'npm run build' in frontend/ directory")
