from fastapi import FastAPI, UploadFile, File, Form, HTTPException, BackgroundTasks, Request, Depends
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional, Dict
import shutil
import os
import tempfile
import random
import uuid
import time
from threading import Thread
import asyncio

from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded

from src.core.llm import get_llm_client
from src.core.generator import FlashcardGenerator
from src.core.schemas import DeckConfig
from src.core.anki import AnkiDeckBuilder
from src.core.images import get_image_generator
from src.core.config import settings
from pypdf import PdfReader

# Setup Rate Limiting
limiter = Limiter(key_func=get_remote_address)
app = FastAPI(title=settings.APP_NAME, version="0.2.0")
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Setup CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-Memory Job Store (Zero-Cost Queue)
jobs: Dict[str, dict] = {}

def cleanup_file(path: str):
    try:
        if os.path.exists(path):
            os.remove(path)
            print(f"DEBUG: Cleaned up {path}")
    except Exception as e:
        print(f"ERROR: Cleaning up {path} failed: {e}")

def get_real_api_key(provider: str, user_key: Optional[str] = None) -> str:
    # 1. User provided key (BYOK)
    if user_key and user_key.strip():
        return user_key
    
    # 2. System ENV key
    env_key = getattr(settings, f"{provider.upper()}_API_KEY", None)
    if env_key:
        return env_key
        
    raise ValueError(f"No API Key found for {provider}. Please provide one.")

def generate_deck_task(job_id: str, text: str, config_data: dict, provider: str, user_key: str, images_enabled: bool):
    try:
        jobs[job_id]["status"] = "processing"
        
        # 1. Initialize LLM
        # Determine strict API key usage
        api_key = get_real_api_key(provider, user_key)
        
        llm_client = get_llm_client(provider, api_key, config_data.get('model_name'))
        generator = FlashcardGenerator(llm_client)

        # 2. Generate Cards
        config = DeckConfig(**config_data)
        cards = generator.generate_flashcards(text, config)
        
        if not cards:
            raise ValueError("No cards generated by AI.")

        # 3. Generate Images (if enabled and allowed)
        image_map = {}
        if images_enabled and settings.ENABLE_IMAGE_GEN:
            # Only Gemini supported for now for System Key, or user provided?
            # For now, simplistic implementation
            img_key = api_key if provider == "gemini" else os.getenv("GEMINI_API_KEY") 
            if img_key:
                img_gen = get_image_generator("gemini", img_key)
                if img_gen:
                    temp_dir = tempfile.mkdtemp()
                    for i, card in enumerate(cards):
                        if card.image_prompt:
                            img_filename = f"card_{i}_{random.randint(1000,9999)}.png"
                            img_path = os.path.join(temp_dir, img_filename)
                            if img_gen.generate_image(card.image_prompt, img_path):
                                image_map[i] = img_path

        # 4. Create .apkg
        builder = AnkiDeckBuilder()
        output_filename = f"{config.name.replace(' ', '_')}.apkg"
        output_path = os.path.join(tempfile.gettempdir(), f"{job_id}_{output_filename}")
        
        if image_map:
            builder.create_apkg_with_images(cards, config.name, output_path, image_map)
        else:
            builder.create_apkg(cards, config.name, output_path)
            
        jobs[job_id]["status"] = "completed"
        jobs[job_id]["file_path"] = output_path
        jobs[job_id]["filename"] = output_filename
        
    except Exception as e:
        print(f"JOB ERROR {job_id}: {e}")
        jobs[job_id]["status"] = "failed"
        jobs[job_id]["error"] = str(e)


@app.get("/api/config")
def get_config():
    """Returns public configuration for the frontend."""
    return {
        "enable_ollama": settings.ENABLE_OLLAMA,
        "enable_images": settings.ENABLE_IMAGE_GEN,
        "env": settings.ENV
    }

@app.post("/generate")
@limiter.limit(settings.RATE_LIMIT_FREE)
async def submit_job(
    request: Request,
    background_tasks: BackgroundTasks,
    file: Optional[UploadFile] = File(None),
    text: Optional[str] = Form(None),
    provider: str = Form("gemini"),
    model: Optional[str] = Form(None),
    api_key: Optional[str] = Form(None), # User provided key
    deck_name: str = Form("MeshCards Deck"),
    difficulty: str = Form("Intermediate"),
    style: str = Form("Mixed"),
    max_cards: int = Form(20),
    images: bool = Form(False),
    custom_instructions: Optional[str] = Form(None)
):
    # Check rate limit bypass
    if api_key and len(api_key) > 10:
        # If user provides their own key, they are effectively "Pro"
        # We can simulate bypassing the limiter here logic-wise, 
        # but slowapi applies via decorator. 
        # Ideally we'd have a separate endpoint or custom dependency.
        # For now, the decorator applies to everyone. 
        # TODO: Advanced rate limiting logic.
        pass

    if not file and not text:
        raise HTTPException(status_code=400, detail="Either file or text must be provided")

    # Read Input
    input_text = ""
    try:
        if text:
            input_text = text
        elif file:
            suffix = os.path.splitext(file.filename)[1]
            with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp_file:
                shutil.copyfileobj(file.file, tmp_file)
                tmp_path = tmp_file.name
            
            if suffix.lower() == ".pdf":
                 reader = PdfReader(tmp_path)
                 for page in reader.pages:
                     input_text += page.extract_text() + "\n"
            else:
                with open(tmp_path, "r", encoding="utf-8") as f:
                    input_text = f.read()
            
            os.remove(tmp_path)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to read input: {str(e)}")

    if not input_text.strip():
        raise HTTPException(status_code=400, detail="Input text is empty")
    
    # Create Job
    job_id = str(uuid.uuid4())
    jobs[job_id] = {
        "status": "pending",
        "created_at": time.time()
    }
    
    config_data = {
        "name": deck_name,
        "difficulty": difficulty,
        "style": style,
        "max_cards": max_cards,
        "model_name": model,
        "custom_instructions": custom_instructions
    }
    
    # Start Task
    background_tasks.add_task(
        generate_deck_task, 
        job_id, 
        input_text, 
        config_data, 
        provider, 
        api_key, 
        images
    )
    
    return {"job_id": job_id, "status": "pending"}

@app.get("/status/{job_id}")
def get_status(job_id: str):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    return {
        "job_id": job_id,
        "status": job["status"],
        "error": job.get("error")
    }

@app.get("/download/{job_id}")
def download_deck(job_id: str, background_tasks: BackgroundTasks):
    if job_id not in jobs:
        raise HTTPException(status_code=404, detail="Job not found")
    
    job = jobs[job_id]
    if job["status"] != "completed":
        raise HTTPException(status_code=400, detail="Job not completed")
    
    file_path = job["file_path"]
    filename = job["filename"]
    
    # Schedule cleanup after response
    background_tasks.add_task(cleanup_file, file_path)
    
    return FileResponse(
        file_path, 
        media_type="application/octet-stream", 
        filename=filename
    )

# Mount static files - MUST BE LAST
app.mount("/", StaticFiles(directory="src/web", html=True), name="static")
